### PR TITLE
feat(React router): Implemented react router dom api example

### PR DESCRIPTION
**Pull request by Aarush-wadhia**

### CODE REVIEW

**Comment by ColdSauce** [comment]
Hey @Aarush-wadhia thanks for the PR! Just a heads up, I think you have the jotai commits in here along with your react router ones.

**Comment by louisgv** [comment]
@Aarush-wadhia can you move the react-router code into its own branch (going from `main`) - it seems the current branch started from your previous react-router commit.

**Comment by Aarush-wadhia** [comment]
> @Aarush-wadhia can you move the react-router code into its own branch tree going from `main` - it seems the current branch started from your previous react-router commit.

Opps!
Let me take care of this issue

**Comment by louisgv** [comment]
I think you might have a stale fork after I merged your jotai example. Tho I think merging this should be fine as it will be squashed anyhow - Great work 🙌

**Comment by Aarush-wadhia** [comment]
My react router branch was a few commits behind which caused the issue I didn't update my main branch. But things are taken care of.
Cheers! 🍻

**Pull request merged**
