### PR TITLE
Add with-svelte-injected-style example

### PR DESCRIPTION
**Pull request by JoacoEsteban**

### CODE REVIEW

**Comment by louisgv** [comment]
Ooh noice! I wonder if we should separate this into its own example, or couple it into the with-svelte :-?

**Comment by JoacoEsteban** [comment]
Hey! I made this draft to show a working example for the changes introduced on https://github.com/PlasmoHQ/plasmo/pull/955 to @avi12.
I guess we could add it to `with-svelte` if you consider this to be the default behavior!

**Comment by avi12** [comment]
IMO it should be in `with-svelte`
Using Svelte's CSS injection renders Plasmo's `getStyle` useless

**Comment by JoacoEsteban** [comment]
Awesome, then i'll add the changes to the with-svelte example and update the PR.

**Comment by JoacoEsteban** [comment]
Hey there! Just updated the PR with what we discussed. Let me know if you want to add/remove anything else.

**Comment by avi12** [comment]
To be honest, it's a good practice to be able to use `getStyle` if you wish to apply CSS globally 
For example, in my extension I'm using it to switch between CSS variables related to dark and light modes, and the advantage is that I only need to edit in one file to affect every other component

**Comment by JoacoEsteban** [comment]
I agree, that's why I left the `getStyles` call for plasmo container styling. I just moved the component styles into the component

**Review by louisgv — APPROVED** [review]
LGTM 👍

**Pull request merged**
